FROM vanzhiganov/xstorage-base:7-1
COPY . /source
COPY ./entrypoint.sh /
WORKDIR /source
# RUN python3 setup.py install
RUN python3 setup.py sdist
RUN pip3 install /source/dist/xStorageServer*
WORKDIR /root
RUN rm -rf /source
EXPOSE 8080
ENTRYPOINT '/entrypoint.sh'
